CREATE TABLE ANAGRAFICA
(
IDanagrafica INT PRIMARY KEY IDENTITY(1,1),
Cognome NVARCHAR(150),
Nome NVARCHAR(150),
Indirizzo NVARCHAR(MAX),
Citta NVARCHAR(150),
CAP NVARCHAR(5),
Cod_Fisc NVARCHAR(16)
)

CREATE TABLE TIPO_VIOLAZIONE (
IDviolazione INT PRIMARY KEY IDENTITY(1,1),
descrizione NVARCHAR(MAX)
)

CREATE TABLE VERBALE
(
IDverbale INT PRIMARY KEY IDENTITY(1,1),
DataViolazione DATE,
IndirizzoViolazione NVARCHAR(MAX),
Nominativo_Agente NVARCHAR(150),
DataTrascrizioneVerbale DATE,
Importo MONEY,
DecurtamentoPunti INT,
IDanagrafica INT FOREIGN KEY REFERENCES ANAGRAFICA(IDanagrafica),
IDviolazione INT FOREIGN KEY REFERENCES TIPO_VIOLAZIONE(IDviolazione)
)